source:  .
baseurl: ""

exclude:
  - .vimlist
  - .projectrc
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - "*.txt"
  - xx*
  - yy* 
  - zz*
  - "*.log"
  - "*.out"
  - junk*


title: russt on github
description: "russt software projects"

name:      Russ Tremian
author:    russt
email: tweet@me
twitter_username: russtman
github_username:  russt

# the base hostname & protocol for your site
#url: "http://russt.github.io/"
