exclude:
  - .vimlist
  - .projectrc
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - "*.txt"
  - xx*
  - yy* 
  - zz*
  - "*.log"
  - "*.out"
  - junk*

encoding: UTF-8

future:      false
lsi:         false
highlighter: pygments

permalink:   date
markdown:    kramdown
excerpt_separator: "\n\n"

author:    russt
name:      Russ Tremian
email: tweet@me
twitter_username: russtman
github_username:  russt

url: "http://russt.github.io/" # the base hostname & protocol for your site
title: russt on github
description: "russt software projects"
